export const DISPLAY_ALERT = "DISPLAY_ALERT"
export const CLEAR_ALERT = "CLEAR_ALERT"

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const LOGOUT_USER = "LOGOUT_USER"

export const HANDLE_CHANGE = "HANDLE_CHANGE"
export const HANDLE_FILE_CHANGE = "HANDLE_FILE_CHANGE"

export const UPLOAD_FILE_BEGIN = "UPLOAD_FILE_BEGIN"
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS"
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR"

export const CLEAR_VALUES = "CLEAR_VALUES"

export const CREATE_PROJECT_BEGIN = "CREATE_PROJECT_BEGIN"
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS"
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR"
export const GET_PROJECT_BEGIN = "GET_PROJECT_BEGIN"
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS"

export const SET_EDIT_PROJECT = "SET_EDIT_PROJECT"

export const EDIT_PROJECT_BEGIN = "EDIT_PROJECT_BEGIN"
export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS"
export const EDIT_PROJECT_ERROR = "EDIT_PROJECT_ERROR"

export const DELETE_PROJECT_BEGIN = "DELETE_PROJECT_BEGIN"

export const FILTER_PROJECTS = "FILTER_PROJECTS"

